/**
 * @file ethercat_plugin.c
 * @brief EtherCAT Plugin Implementation for OpenPLC Runtime v4
 *
 * This plugin implements one or more EtherCAT masters using the SOEM library.
 * It consumes the ethercat.json configuration generated by the OpenPLC Editor
 * and manages the EtherCAT bus lifecycle with an explicit state machine.
 *
 * Multi-master support:
 *   - Each JSON entry with "protocol":"ETHERCAT" becomes an independent master
 *     instance with its own SOEM context, IOmap, channel map, and monitor thread.
 *   - The plugin-wide logger and runtime args are shared across all masters.
 *
 * Phase 1: Config parsing, SOEM init, topology validation
 * Phase 2: SDO writes, PDO mapping, state transition to OPERATIONAL
 * Phase 3: Synchronous process data exchange within PLC scan cycle
 *
 * Architecture:
 *   - Process data exchange runs synchronously inside the PLC scan cycle
 *     via cycle_start/cycle_end hooks, sharing the PLC thread's timing.
 *   - cycle_start: writes outputs, exchanges process data, reads inputs
 *   - cycle_end: (no-op, outputs are sent at the start of the next cycle)
 *   - No separate EtherCAT thread or shadow buffer is needed.
 */

#include <ctype.h>
#include <stdatomic.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdbool.h>
#include <pthread.h>
#include <time.h>
#include <unistd.h>

#include "plugin_logger.h"
#include "plugin_types.h"
#include "ethercat_plugin.h"
#include "ethercat_config.h"
#include "ethercat_master.h"
#include "ethercat_io.h"
#include "soem/soem.h"   /* osal_get_monotonic_time, ec_timet */
#include "cjson/cJSON.h"  /* JSON parsing for execute_command */

/*
 * =============================================================================
 * Constants
 * =============================================================================
 */

/** Minimum timeout for receive in microseconds */
#define ECAT_MIN_RECEIVE_TIMEOUT_US 200

/*
 * =============================================================================
 * Inline Timing Helpers
 * =============================================================================
 */

/**
 * @brief Convert ec_timet (struct timespec) to nanoseconds
 */
static inline uint64_t timespec_to_ns(const ec_timet *ts)
{
    return (uint64_t)ts->tv_sec * 1000000000ULL + (uint64_t)ts->tv_nsec;
}

/**
 * @brief Return elapsed nanoseconds between two timestamps
 */
static inline uint64_t elapsed_ns(const ec_timet *start, const ec_timet *end)
{
    uint64_t s = timespec_to_ns(start);
    uint64_t e = timespec_to_ns(end);
    return (e > s) ? (e - s) : 0;
}

/*
 * =============================================================================
 * EtherCAT AL State to String Helper
 * =============================================================================
 */

/**
 * @brief Convert SOEM EC_STATE_* value to a human-readable string
 */
static const char *al_state_to_string(uint16_t state)
{
    /* Mask off the error bit for comparison */
    uint16_t base = state & 0x0F;
    int has_error = (state & EC_STATE_ERROR) != 0;

    const char *name;
    switch (base) {
    case EC_STATE_NONE:     name = "NONE";     break;
    case EC_STATE_INIT:     name = "INIT";     break;
    case EC_STATE_PRE_OP:   name = "PRE-OP";   break;
    case EC_STATE_BOOT:     name = "BOOT";     break;
    case EC_STATE_SAFE_OP:  name = "SAFE-OP";  break;
    case EC_STATE_OPERATIONAL: name = "OP";     break;
    default:                name = "UNKNOWN";  break;
    }

    /* Return static strings for common cases */
    if (!has_error)
        return name;

    /* For error states, we just note it. Since we return static strings,
     * use a small set of pre-defined error state strings. */
    switch (base) {
    case EC_STATE_INIT:    return "INIT+ERR";
    case EC_STATE_PRE_OP:  return "PRE-OP+ERR";
    case EC_STATE_SAFE_OP: return "SAFE-OP+ERR";
    default:               return "UNKNOWN+ERR";
    }
}

/*
 * =============================================================================
 * Local String Helper
 * =============================================================================
 */

static void safe_strcpy_local(char *dest, const char *src, size_t max_len)
{
    if (src == NULL) { dest[0] = '\0'; return; }
    strncpy(dest, src, max_len - 1);
    dest[max_len - 1] = '\0';
}

/*
 * =============================================================================
 * Diag Reset Helper
 * =============================================================================
 *
 * Runs before the monitor thread is created and before the PLC enters
 * OPERATIONAL — no concurrency yet, so memset is sufficient to zero the
 * atomic fields.  The min sentinel starts at UINT64_MAX so the first
 * cycle's "less-than" comparison wins.
 */
static void diag_reset(ecat_cycle_diag_t *d)
{
    memset(d, 0, sizeof(*d));
    atomic_store_explicit(&d->min_bus_cycle_ns, UINT64_MAX, memory_order_relaxed);
}

/*
 * =============================================================================
 * Mutex Init Helper
 * =============================================================================
 *
 * Initializes a mutex with PTHREAD_PRIO_INHERIT so that the SCHED_FIFO PLC
 * thread does not get blocked behind a normal-priority thread that holds
 * the same lock (priority inversion).  Falls back gracefully on platforms
 * that do not support the protocol attribute.
 */
static int ecat_mutex_init_pi(pthread_mutex_t *m)
{
    pthread_mutexattr_t attr;
    if (pthread_mutexattr_init(&attr) != 0)
        return -1;
#if !defined(__CYGWIN__) && !defined(_WIN32)
    /* Best-effort: ignore failure (some libcs return ENOTSUP) */
    (void)pthread_mutexattr_setprotocol(&attr, PTHREAD_PRIO_INHERIT);
#endif
    int rc = pthread_mutex_init(m, &attr);
    pthread_mutexattr_destroy(&attr);
    return rc;
}


/*
 * =============================================================================
 * Plugin-Wide State
 * =============================================================================
 *
 * The logger and runtime args are shared across all masters.
 * Per-master state is in the g_masters[] array.
 */

static plugin_logger_t g_logger;
static plugin_runtime_args_t g_runtime_args;
static ecat_master_instance_t *g_masters = NULL;  /* heap-allocated array */
static int g_master_count = 0;

/*
 * =============================================================================
 * Per-Instance Slaves Snapshot
 * =============================================================================
 */

/**
 * @brief Build and publish a snapshot of per-slave AL state.
 *
 * Reads from ecx_context.slavelist[] and config.slaves[] into a stack
 * array, then memcpy-publishes under slaves_mutex.  The caller must
 * hold soem_lock when calling this (the read of slavelist[] races with
 * monitor recovery otherwise).
 *
 * Counters/timing are NOT cached here -- consumers (build_master_*_json)
 * read them lock-free via atomic_load directly from inst->diag.
 */
static void publish_slaves_snapshot(ecat_master_instance_t *inst)
{
    ecat_slave_status_t local[ECAT_MAX_SLAVES];
    memset(local, 0, sizeof(local));

    int n = inst->config.slave_count;
    if (n > ECAT_MAX_SLAVES)
        n = ECAT_MAX_SLAVES;

    for (int i = 0; i < n; i++) {
        const ecat_slave_t *cfg = &inst->config.slaves[i];
        ecat_slave_status_t *ss = &local[i];

        ss->position = cfg->position;
        strncpy(ss->name, cfg->name, ECAT_MAX_NAME_LEN - 1);
        ss->name[ECAT_MAX_NAME_LEN - 1] = '\0';

        const ec_slavet *soem = ecat_master_get_slave(inst, cfg->position);
        if (soem) {
            ss->al_state = soem->state;
            ss->al_status_code = soem->ALstatuscode;
        }
    }

    pthread_mutex_lock(&inst->slaves_mutex);
    memcpy(inst->slaves_snapshot, local, sizeof(local));
    inst->slaves_snapshot_count = n;
    pthread_mutex_unlock(&inst->slaves_mutex);
}

#if ECAT_ENABLE_MONITOR_THREAD
/*
 * =============================================================================
 * Recovery Logic (runs in monitor thread, never in PLC scan cycle)
 * =============================================================================
 */

/**
 * @brief Attempt to recover all slaves that are not in OP
 *
 * MUST be called with inst->soem_lock held (the monitor thread takes it
 * before calling), because these SOEM calls are blocking and not
 * thread-safe versus the PLC's exchange.
 *
 * @param inst Per-master instance
 * @return 1 if all slaves back in OP, 0 if some still recovering, -1 on max attempts
 */
static int attempt_recovery(ecat_master_instance_t *inst)
{
    ecat_master_read_states(inst);

    int all_ok = 1;

    for (int i = 0; i < inst->config.slave_count; i++) {
        int pos = inst->config.slaves[i].position;
        uint16_t state = ecat_master_get_slave_state(inst, pos);

        if (state != EC_STATE_OPERATIONAL) {
            all_ok = 0;
            int result = ecat_master_recover_slave(inst, pos, &g_logger);
            if (result < 0) {
                plugin_logger_error(&g_logger,
                    "Master '%s': Slave %d (%s): recovery error",
                    inst->name, pos, inst->config.slaves[i].name);
            }
        }
    }

    if (all_ok) {
        plugin_logger_info(&g_logger,
            "Master '%s': All slaves recovered to OPERATIONAL (attempts=%d)",
            inst->name, atomic_load(&inst->recovery_attempts));
        atomic_store(&inst->recovery_attempts, 0);
        atomic_store(&inst->consecutive_wkc_errors, 0);
        return 1;
    }

    /* Single-writer (monitor thread) — fetch_add not needed; load+store is
     * sufficient and communicates the ownership model. */
    int attempts = atomic_load_explicit(&inst->recovery_attempts,
                                        memory_order_relaxed) + 1;
    atomic_store_explicit(&inst->recovery_attempts, attempts,
                          memory_order_relaxed);

    if (attempts >= ECAT_MAX_RECOVERY_ATTEMPTS) {
        plugin_logger_error(&g_logger,
            "Master '%s': Maximum recovery attempts (%d) reached - transitioning to ERROR",
            inst->name, ECAT_MAX_RECOVERY_ATTEMPTS);
        return -1;
    }

    plugin_logger_warn(&g_logger,
        "Master '%s': Recovery attempt %d/%d - some slaves not yet in OP",
        inst->name, attempts, ECAT_MAX_RECOVERY_ATTEMPTS);
    return 0;
}

/*
 * =============================================================================
 * Background Monitor Thread (per-instance)
 * =============================================================================
 */

/**
 * @brief Background thread for slave state monitoring, recovery, and logging.
 *
 * Runs at default (non-RT) priority.  Periodically:
 *   - Acquires inst->soem_lock (PLC trylocks the same mutex; if the
 *     monitor is holding it, the PLC skips one exchange cycle).
 *   - Reads slave states via ecx_readstate() and publishes the slaves
 *     snapshot.
 *   - Performs recovery if in RECOVERING state.
 *   - Emits user-facing log messages on state and counter transitions
 *     so the PLC hot path never calls plugin_logger_* (which serialises
 *     on a global mutex and writes synchronously to a Unix socket).
 *
 * @param arg Pointer to the ecat_master_instance_t for this master
 */
static void *ecat_monitor_thread(void *arg)
{
    ecat_master_instance_t *inst = (ecat_master_instance_t *)arg;

    /* Local state for transition-based logging.  All scoped to this
     * thread, so no atomics or struct fields needed.  Stats are only
     * emitted on transitions (state change, WKC errors start/clear) --
     * continuous metrics are already exposed via the status / diagnostics
     * commands consumed by the editor. */
    int last_logged_state = -1;
    int last_logged_consec_wkc = 0;

    plugin_logger_info(&g_logger,
        "Master '%s': monitor thread started (interval=%d ms)",
        inst->name, ECAT_MONITOR_INTERVAL_MS);

    while (atomic_load(&inst->monitor_running)) {
        int state = atomic_load(&inst->plugin_state);

        if (state == ECAT_STATE_OPERATIONAL) {
            /* Periodic state check.  Publish slaves snapshot while still
             * holding the lock, so the read of slavelist[] is consistent. */
            pthread_mutex_lock(&inst->soem_lock);
            ecat_master_read_states(inst);
            publish_slaves_snapshot(inst);
            pthread_mutex_unlock(&inst->soem_lock);

        } else if (state == ECAT_STATE_RECOVERING) {
            /* Recovery holds the lock for longer; PLC will skip cycles. */
            pthread_mutex_lock(&inst->soem_lock);
            int result = attempt_recovery(inst);
            publish_slaves_snapshot(inst);
            pthread_mutex_unlock(&inst->soem_lock);

            if (result == 1) {
                atomic_store(&inst->plugin_state, ECAT_STATE_OPERATIONAL);
                plugin_logger_info(&g_logger,
                    "Master '%s': [state: OPERATIONAL] Recovered from error",
                    inst->name);
            } else if (result == -1) {
                atomic_store(&inst->plugin_state, ECAT_STATE_ERROR);
                plugin_logger_error(&g_logger,
                    "Master '%s': entered ERROR state after max recovery attempts",
                    inst->name);
            }
        }

        /* --- Transition-based logging (replaces hot-path PLC logs) --- */

        int curr_state = atomic_load(&inst->plugin_state);
        if (curr_state != last_logged_state) {
            if (curr_state == ECAT_STATE_RECOVERING) {
                plugin_logger_warn(&g_logger,
                    "Master '%s': WKC error threshold (%d) reached, "
                    "[state: RECOVERING]",
                    inst->name, ECAT_WKC_ERROR_THRESHOLD);
            }
            last_logged_state = curr_state;
        }

        int consec = atomic_load(&inst->consecutive_wkc_errors);
        if (consec > 0 && last_logged_consec_wkc == 0) {
            plugin_logger_warn(&g_logger,
                "Master '%s': WKC errors detected (consecutive=%d, expected=%d)",
                inst->name, consec, inst->expected_wkc);
            last_logged_consec_wkc = consec;
        } else if (consec == 0 && last_logged_consec_wkc != 0) {
            plugin_logger_info(&g_logger,
                "Master '%s': WKC errors cleared", inst->name);
            last_logged_consec_wkc = 0;
        }

        /* Sleep for the monitor interval */
        struct timespec sleep_ts;
        sleep_ts.tv_sec = ECAT_MONITOR_INTERVAL_MS / 1000;
        sleep_ts.tv_nsec = (ECAT_MONITOR_INTERVAL_MS % 1000) * 1000000L;
        nanosleep(&sleep_ts, NULL);
    }

    plugin_logger_info(&g_logger, "Master '%s': monitor thread exiting", inst->name);
    return NULL;
}
#endif /* ECAT_ENABLE_MONITOR_THREAD */

/*
 * =============================================================================
 * Per-Instance Helpers for start_loop / stop_loop / cycle_start
 * =============================================================================
 */

/**
 * @brief Start a single EtherCAT master instance
 *
 * Runs through SCANNING -> CONFIGURING -> TRANSITIONING -> OPERATIONAL
 * for one master. On failure the instance is set to ERROR state.
 *
 * @param inst Per-master instance
 * @return 0 on success, -1 on failure
 */
static int start_single_master(ecat_master_instance_t *inst)
{
    if (inst->config.slave_count == 0) {
        plugin_logger_warn(&g_logger,
            "Master '%s': No slaves configured - skipping", inst->name);
        return -1;
    }

    /* --- Phase 1: SCANNING --- */
    atomic_store(&inst->plugin_state, ECAT_STATE_SCANNING);
    plugin_logger_info(&g_logger,
        "Master '%s': [state: SCANNING] Opening interface and scanning bus...",
        inst->name);

    if (ecat_master_open_and_scan(inst, &g_logger) != 0) {
        plugin_logger_error(&g_logger, "Master '%s': Bus scan failed", inst->name);
        atomic_store(&inst->plugin_state, ECAT_STATE_ERROR);
        return -1;
    }

    /* --- Phase 2: CONFIGURING (SDO writes + PDO mapping) --- */
    atomic_store(&inst->plugin_state, ECAT_STATE_CONFIGURING);
    plugin_logger_info(&g_logger,
        "Master '%s': [state: CONFIGURING] Writing SDOs and mapping process data...",
        inst->name);

    /* Write SDOs for each slave that has them configured.  When
     * slave->strict_sdo is true (default) any failed write aborts the
     * master so it never enters OPERATIONAL with a half-configured slave. */
    for (int i = 0; i < inst->config.slave_count; i++) {
        const ecat_slave_t *slave = &inst->config.slaves[i];
        if (slave->sdo_count == 0)
            continue;

        int rc = ecat_master_write_sdos(inst, slave->position, slave->sdo_configs,
                                        slave->sdo_count,
                                        slave->timeouts.sdo_timeout_ms, &g_logger);
        if (rc != 0 && slave->strict_sdo) {
            plugin_logger_error(&g_logger,
                "Master '%s': Slave %d (%s): SDO config failed and strict_sdo=true -- aborting startup",
                inst->name, slave->position, slave->name);
            ecat_master_close(inst, &g_logger);
            atomic_store(&inst->plugin_state, ECAT_STATE_ERROR);
            return -1;
        }
    }

    /* Map process data and configure DC */
    if (ecat_master_configure(inst, &g_logger) != 0) {
        plugin_logger_error(&g_logger,
            "Master '%s': Process data mapping failed", inst->name);
        ecat_master_close(inst, &g_logger);
        atomic_store(&inst->plugin_state, ECAT_STATE_ERROR);
        return -1;
    }

    /* Build channel map for process data exchange.  Partial maps are
     * rejected -- the operator must fix the JSON before the master can
     * enter OPERATIONAL with stale variable bindings. */
    if (ecat_io_build_channel_map(&inst->config, &inst->channel_map,
                                  inst, &g_runtime_args, &g_logger) != 0) {
        plugin_logger_error(&g_logger,
            "Master '%s': channel map build failed -- aborting startup",
            inst->name);
        ecat_master_close(inst, &g_logger);
        atomic_store(&inst->plugin_state, ECAT_STATE_ERROR);
        return -1;
    }

    /* Build pre-resolved transfer list for fast per-cycle I/O */
    if (ecat_io_build_transfer_list(&inst->channel_map, &inst->transfer_list,
                                    &g_runtime_args, &g_logger) != 0) {
        plugin_logger_error(&g_logger,
            "Master '%s': transfer list build failed -- aborting startup",
            inst->name);
        ecat_master_close(inst, &g_logger);
        atomic_store(&inst->plugin_state, ECAT_STATE_ERROR);
        return -1;
    }

    /* Cache expected WKC */
    inst->expected_wkc = ecat_master_get_expected_wkc(inst);
    plugin_logger_info(&g_logger, "Master '%s': Expected WKC: %d",
                       inst->name, inst->expected_wkc);

    inst->receive_timeout_us = inst->config.master.receive_timeout_us;
    if (inst->receive_timeout_us < ECAT_MIN_RECEIVE_TIMEOUT_US)
        inst->receive_timeout_us = ECAT_MIN_RECEIVE_TIMEOUT_US;
    plugin_logger_info(&g_logger,
        "Master '%s': Receive timeout: %d us (cycle_time=%d us)",
        inst->name, inst->receive_timeout_us, inst->config.master.cycle_time_us);

    /* --- Phase 3: TRANSITIONING --- */
    atomic_store(&inst->plugin_state, ECAT_STATE_TRANSITIONING);
    plugin_logger_info(&g_logger,
        "Master '%s': [state: TRANSITIONING] Moving slaves to OPERATIONAL...",
        inst->name);

    if (ecat_master_transition_to_op(inst, &g_logger) != 0) {
        plugin_logger_error(&g_logger,
            "Master '%s': Failed to reach OPERATIONAL state", inst->name);
        ecat_master_close(inst, &g_logger);
        atomic_store(&inst->plugin_state, ECAT_STATE_ERROR);
        return -1;
    }

    /* --- Phase 4: OPERATIONAL --- */
    atomic_store(&inst->consecutive_wkc_errors, 0);
    atomic_store(&inst->recovery_attempts, 0);
    inst->cycle_counter = 0;
    diag_reset(&inst->diag);

    atomic_store(&inst->plugin_state, ECAT_STATE_OPERATIONAL);

    /* Send one initial exchange to populate the IOmap with slave data */
    ecat_master_exchange_processdata(inst, inst->receive_timeout_us);

    /* Initial publish before the monitor thread starts.  No concurrency
     * yet: PLC has not entered cycle_start_single and the monitor does
     * not exist. */
    publish_slaves_snapshot(inst);

#if ECAT_ENABLE_MONITOR_THREAD
    /* Start background monitor thread for state checks and recovery.
     * soem_lock is initialized in init() once per instance. */
    atomic_store(&inst->exchange_skips, 0);
    atomic_store(&inst->monitor_running, true);

    if (pthread_create(&inst->monitor_thread, NULL, ecat_monitor_thread, inst) != 0) {
        plugin_logger_warn(&g_logger,
            "Master '%s': Failed to create monitor thread - "
            "running without state monitoring", inst->name);
        atomic_store(&inst->monitor_running, false);
    }
#endif

    /* Per-iface external state (NIC tuning + IP isolation) is applied
     * inside ecat_master_open_and_scan() and reverted inside
     * ecat_master_close(). */

    plugin_logger_info(&g_logger,
        "Master '%s': [state: OPERATIONAL] EtherCAT master started "
        "(synchronous exchange, monitor=%s)",
        inst->name, ECAT_ENABLE_MONITOR_THREAD ? "enabled" : "disabled");

    return 0;
}

/**
 * @brief Stop a single master instance
 *
 * Stops the monitor thread, logs final diagnostics, and closes the master.
 *
 * @param inst Per-master instance
 */
static void stop_single_master(ecat_master_instance_t *inst)
{
    int state = atomic_load(&inst->plugin_state);
    if (state == ECAT_STATE_STOPPED || state == ECAT_STATE_IDLE) {
        plugin_logger_debug(&g_logger,
            "Master '%s': already stopped/idle", inst->name);
        return;
    }

    plugin_logger_info(&g_logger,
        "Master '%s': Stopping (current state: %s)...",
        inst->name, ecat_state_to_string(state));

#if ECAT_ENABLE_MONITOR_THREAD
    /* Stop the monitor thread before closing the master */
    if (atomic_load(&inst->monitor_running)) {
        atomic_store(&inst->monitor_running, false);
        pthread_join(inst->monitor_thread, NULL);
        plugin_logger_debug(&g_logger,
            "Master '%s': Monitor thread joined", inst->name);
    }
#endif

    /* Log final diagnostics via relaxed atomic loads.  PLC may still be
     * running (it stops at the next state check); cross-field tearing is
     * harmless here. */
    uint64_t final_cycle_count =
        atomic_load_explicit(&inst->diag.cycle_count, memory_order_relaxed);
    uint64_t final_wkc_errors =
        atomic_load_explicit(&inst->diag.wkc_error_count, memory_order_relaxed);
    int64_t  final_avg =
        atomic_load_explicit(&inst->diag.avg_bus_cycle_ns, memory_order_relaxed);
    uint64_t final_min =
        atomic_load_explicit(&inst->diag.min_bus_cycle_ns, memory_order_relaxed);
    uint64_t final_max =
        atomic_load_explicit(&inst->diag.max_bus_cycle_ns, memory_order_relaxed);

    if (final_cycle_count > 0 || final_wkc_errors > 0) {
        uint64_t total_cycles = final_cycle_count + final_wkc_errors;
        /* min sentinel UINT64_MAX -> "n/a" */
        unsigned long long min_us = (final_min == UINT64_MAX) ? 0
                                  : (unsigned long long)(final_min / 1000);
        plugin_logger_info(&g_logger,
            "Master '%s': Final cycle stats: %llu total (%llu ok, %llu errors), "
            "avg=%lld us, min=%llu us, max=%llu us",
            inst->name,
            (unsigned long long)total_cycles,
            (unsigned long long)final_cycle_count,
            (unsigned long long)final_wkc_errors,
            (long long)(final_avg / 1000),
            min_us,
            (unsigned long long)(final_max / 1000));
    }

    /* IP-stack isolation revert happens inside ecat_master_close(). */

    memset(&inst->channel_map, 0, sizeof(inst->channel_map));
    memset(&inst->transfer_list, 0, sizeof(inst->transfer_list));
    atomic_store(&inst->consecutive_wkc_errors, 0);
    atomic_store(&inst->recovery_attempts, 0);
    inst->expected_wkc = 0;

    ecat_master_close(inst, &g_logger);
    atomic_store(&inst->plugin_state, ECAT_STATE_STOPPED);

    /* Reset slaves snapshot: the bus is closed, AL states from the prior
     * run are no longer meaningful.  Monitor is already joined. */
    pthread_mutex_lock(&inst->slaves_mutex);
    memset(inst->slaves_snapshot, 0, sizeof(inst->slaves_snapshot));
    inst->slaves_snapshot_count = 0;
    pthread_mutex_unlock(&inst->slaves_mutex);

    plugin_logger_info(&g_logger,
        "Master '%s': [state: STOPPED] EtherCAT master stopped", inst->name);
}

/**
 * @brief Run one cycle for a single master instance
 *
 * Performs synchronous EtherCAT process data exchange:
 *   1. Writes PLC outputs (from previous cycle) into the real IOmap
 *   2. Exchanges process data with all slaves via SOEM
 *   3. Reads received inputs from the IOmap into PLC input buffers
 *   4. Tracks WKC errors (no blocking SOEM calls)
 *
 * @param inst Per-master instance
 */
static void cycle_start_single(ecat_master_instance_t *inst)
{
    int state = atomic_load(&inst->plugin_state);
    /* RECOVERING is allowed: opportunistic exchange in the gaps between
     * monitor recovery attempts.  exchange_skips counts trylock misses. */
    if (state != ECAT_STATE_OPERATIONAL && state != ECAT_STATE_RECOVERING)
        return;

    /* Task-based scheduling: skip cycles that don't align with the task interval.
     * tick_divisor is always >= 1; when 1 the modulo is always 0 (no skip). */
    if ((inst->cycle_counter % inst->tick_divisor) != 0) {
        inst->cycle_counter++;
        return;
    }

    uint8_t *iomap = ecat_master_get_iomap(inst);
    if (!iomap)
        return;

#if ECAT_ENABLE_MONITOR_THREAD
    /* If the monitor thread is holding soem_lock (state check or recovery),
     * yield this cycle.  The PLC keeps running with stale I/O data for one
     * cycle.  Trylock is non-blocking; in contention it costs only a futex
     * read and returns immediately. */
    if (pthread_mutex_trylock(&inst->soem_lock) != 0) {
        atomic_fetch_add(&inst->exchange_skips, 1);
        return;
    }
#endif

    /* 1. Write PLC outputs to IOmap (from previous cycle's computation) */
    ecat_io_write_outputs_fast(&inst->transfer_list, iomap);

    /* 2. Exchange process data with slaves (synchronous) */
    ec_timet t0, t1;
    osal_get_monotonic_time(&t0);
    int wkc = ecat_master_exchange_processdata(inst, inst->receive_timeout_us);
    osal_get_monotonic_time(&t1);

    uint64_t exchange_ns = elapsed_ns(&t0, &t1);

    /* 3. Read received inputs into PLC buffers */
    ecat_io_read_inputs_fast(&inst->transfer_list, iomap);

#if ECAT_ENABLE_MONITOR_THREAD
    pthread_mutex_unlock(&inst->soem_lock);
#endif

    inst->cycle_counter++;

    bool wkc_error = (wkc < inst->expected_wkc);
    bool noframe   = (wkc == EC_NOFRAME);

    /* Update diag lock-free.  Single-writer (PLC) + relaxed atomics; readers
     * tolerate cross-field tearing because diagnostics never do cross-field
     * arithmetic.  bus_cycle_ns measures the bus exchange (send+receive); the
     * memcpy work in read/write_inputs_fast is dwarfed by it and intentionally
     * not measured. */
    atomic_store_explicit(&inst->diag.bus_cycle_ns, exchange_ns, memory_order_relaxed);

    if (wkc_error) {
        atomic_fetch_add_explicit(&inst->diag.wkc_error_count, 1,
                                  memory_order_relaxed);
        if (noframe)
            atomic_fetch_add_explicit(&inst->diag.noframe_count, 1,
                                      memory_order_relaxed);
    }

    atomic_fetch_add_explicit(&inst->diag.cycle_count, 1, memory_order_relaxed);

    /* EWMA: avg += (sample - avg) >> SHIFT.  Tracks recent-window jitter
     * instead of a historical mean (which the previous integer-Welford
     * loop stalled at once cycle_count grew large).  Signed right shift
     * is implementation-defined in C but is arithmetic on GCC/Clang,
     * which the runtime already depends on. */
    int64_t cur_avg = atomic_load_explicit(&inst->diag.avg_bus_cycle_ns,
                                           memory_order_relaxed);
    cur_avg += ((int64_t)exchange_ns - cur_avg) >> ECAT_AVG_EWMA_SHIFT;
    atomic_store_explicit(&inst->diag.avg_bus_cycle_ns, cur_avg,
                          memory_order_relaxed);

    /* Min/max: single-writer, no CAS needed. */
    uint64_t cur = atomic_load_explicit(&inst->diag.max_bus_cycle_ns,
                                        memory_order_relaxed);
    if (exchange_ns > cur)
        atomic_store_explicit(&inst->diag.max_bus_cycle_ns, exchange_ns,
                              memory_order_relaxed);

    cur = atomic_load_explicit(&inst->diag.min_bus_cycle_ns,
                               memory_order_relaxed);
    if (exchange_ns < cur)
        atomic_store_explicit(&inst->diag.min_bus_cycle_ns, exchange_ns,
                              memory_order_relaxed);

    /* WKC error tracking.  No plugin_logger_* calls here -- the runtime
     * logger does a synchronous mutex+socket write that would inject
     * jitter in the hot path.  The monitor thread observes these counters
     * and emits the user-facing log messages. */
    if (wkc_error) {
        int consec = atomic_fetch_add(&inst->consecutive_wkc_errors, 1) + 1;
#if ECAT_ENABLE_MONITOR_THREAD
        if (state == ECAT_STATE_OPERATIONAL &&
            consec >= ECAT_WKC_ERROR_THRESHOLD) {
            atomic_store(&inst->plugin_state, ECAT_STATE_RECOVERING);
        }
#else
        (void)consec;
#endif
    } else {
        atomic_store(&inst->consecutive_wkc_errors, 0);
    }
}

/*
 * =============================================================================
 * Plugin Lifecycle Functions
 * =============================================================================
 */

/**
 * @brief Initialize the EtherCAT plugin
 */
int init(void *args)
{
    /* Initialize logger first (before we have runtime_args) */
    plugin_logger_init(&g_logger, "ETHERCAT", NULL);
    plugin_logger_info(&g_logger, "Initializing EtherCAT plugin...");

    if (!args) {
        plugin_logger_error(&g_logger, "init args is NULL");
        return -1;
    }

    /* Copy runtime args (critical - pointer is freed after init returns) */
    memcpy(&g_runtime_args, args, sizeof(plugin_runtime_args_t));

    /* Re-initialize logger with runtime_args for central logging */
    plugin_logger_init(&g_logger, "ETHERCAT", args);

    /* Share the logger with the config parser so its diagnostic messages
     * land in the runtime journal instead of stderr. */
    ecat_config_set_logger(&g_logger);

    plugin_logger_info(&g_logger, "Buffer size: %d", g_runtime_args.buffer_size);

    /* Parse ALL master configurations from the JSON file */
    const char *config_path = g_runtime_args.plugin_specific_config_file_path;

    /* Allocate temporary array for parsing (up to ECAT_MAX_MASTERS) */
    ecat_master_instance_t *temp = calloc(ECAT_MAX_MASTERS, sizeof(ecat_master_instance_t));
    if (!temp) {
        plugin_logger_error(&g_logger, "Failed to allocate master instances");
        return -1;
    }

    int count = 0;
    if (config_path != NULL && config_path[0] != '\0') {
        plugin_logger_info(&g_logger, "Loading config: %s", config_path);
        int result = ecat_config_parse_all(config_path, temp, ECAT_MAX_MASTERS, &count);
        if (result != ECAT_CONFIG_OK || count == 0) {
            plugin_logger_warn(&g_logger,
                "No valid EtherCAT configs found (result=%d, count=%d), using defaults",
                result, count);
            ecat_config_init_defaults(&temp[0].config);
            safe_strcpy_local(temp[0].name, "default", sizeof(temp[0].name));
            count = 1;
        } else {
            plugin_logger_info(&g_logger,
                "Configuration loaded: %d master(s) found", count);
        }
    } else {
        plugin_logger_warn(&g_logger, "No config file specified, using defaults");
        ecat_config_init_defaults(&temp[0].config);
        safe_strcpy_local(temp[0].name, "default", sizeof(temp[0].name));
        count = 1;
    }

    /* Store the master instances */
    g_masters = temp;
    g_master_count = count;

    /* Initialize per-master runtime state */
    for (int i = 0; i < g_master_count; i++) {
        ecat_master_instance_t *inst = &g_masters[i];

        memset(inst->slaves_snapshot, 0, sizeof(inst->slaves_snapshot));
        inst->slaves_snapshot_count = 0;
        diag_reset(&inst->diag);
        if (ecat_mutex_init_pi(&inst->slaves_mutex) != 0) {
            plugin_logger_error(&g_logger,
                "Master[%d] '%s': Failed to initialize slaves mutex", i, inst->name);
            /* Destroy mutexes that were already initialized */
            for (int j = 0; j < i; j++) {
                pthread_mutex_destroy(&g_masters[j].slaves_mutex);
#if ECAT_ENABLE_MONITOR_THREAD
                pthread_mutex_destroy(&g_masters[j].soem_lock);
#endif
            }
            free(g_masters);
            g_masters = NULL;
            g_master_count = 0;
            return -1;
        }
#if ECAT_ENABLE_MONITOR_THREAD
        if (ecat_mutex_init_pi(&inst->soem_lock) != 0) {
            plugin_logger_error(&g_logger,
                "Master[%d] '%s': Failed to initialize SOEM lock", i, inst->name);
            pthread_mutex_destroy(&inst->slaves_mutex);
            for (int j = 0; j < i; j++) {
                pthread_mutex_destroy(&g_masters[j].slaves_mutex);
                pthread_mutex_destroy(&g_masters[j].soem_lock);
            }
            free(g_masters);
            g_masters = NULL;
            g_master_count = 0;
            return -1;
        }
#endif

        /* Calculate tick divisor for task-based scheduling.
         * A divisor of 1 means "execute every cycle" (the default). */
        inst->tick_divisor = 1;
        if (inst->config.master.task_cycle_time_us > 0 &&
            g_runtime_args.common_ticktime_ns > 0) {
            unsigned long long task_ns =
                (unsigned long long)inst->config.master.task_cycle_time_us * 1000ULL;
            unsigned int divisor = (unsigned int)(task_ns / g_runtime_args.common_ticktime_ns);
            if (divisor > 1)
                inst->tick_divisor = divisor;
            plugin_logger_info(&g_logger,
                "Master[%d] '%s': task=%s, task_cycle=%d us, base_tick=%llu ns, divisor=%u",
                i, inst->name, inst->config.master.task_name,
                inst->config.master.task_cycle_time_us,
                (unsigned long long)g_runtime_args.common_ticktime_ns,
                inst->tick_divisor);
        }

        atomic_store(&inst->plugin_state, ECAT_STATE_IDLE);

        plugin_logger_info(&g_logger,
            "Master[%d] '%s': interface=%s, cycle_time=%d us, slaves=%d",
            i, inst->name, inst->config.master.interface,
            inst->config.master.cycle_time_us, inst->config.slave_count);
    }

    plugin_logger_info(&g_logger,
        "EtherCAT plugin initialized [%d master(s), state: IDLE]", g_master_count);

    return 0;
}

/*
 * =============================================================================
 * IEC Address Overlap Detection (multi-master)
 * =============================================================================
 */

/**
 * @brief Compute the byte range [start, end) occupied by a channel map entry
 */
static void entry_byte_range(const ecat_channel_map_entry_t *e,
                             int *start, int *end)
{
    *start = e->byte_index;
    switch (e->size) {
    case IEC_SIZE_BIT:   *end = e->byte_index + 1; break;
    case IEC_SIZE_BYTE:  *end = e->byte_index + 1; break;
    case IEC_SIZE_WORD:  *end = e->byte_index + 2; break;
    case IEC_SIZE_DWORD: *end = e->byte_index + 4; break;
    case IEC_SIZE_LWORD: *end = e->byte_index + 8; break;
    default:             *end = e->byte_index + 1; break;
    }
}

/**
 * @brief Check if two channel map entries overlap in the PLC buffer
 *
 * For bit-sized entries at the same byte, also checks bit_index equality.
 */
static bool entries_overlap(const ecat_channel_map_entry_t *a,
                            const ecat_channel_map_entry_t *b)
{
    int a_start, a_end, b_start, b_end;
    entry_byte_range(a, &a_start, &a_end);
    entry_byte_range(b, &b_start, &b_end);

    if (a_end <= b_start || b_end <= a_start)
        return false;

    if (a->size == IEC_SIZE_BIT && b->size == IEC_SIZE_BIT
        && a->byte_index == b->byte_index) {
        return a->bit_index == b->bit_index;
    }

    return true;
}

/**
 * @brief Log warnings for IEC addresses mapped by more than one master
 *
 * Called after all masters have built their channel maps. Checks both
 * input and output directions. Purely informational -- does not abort.
 */
static void warn_address_overlap(void)
{
    if (g_master_count < 2)
        return;

    int conflicts = 0;

    for (int i = 0; i < g_master_count; i++) {
        for (int j = i + 1; j < g_master_count; j++) {
            /* Check inputs */
            for (int ai = 0; ai < g_masters[i].channel_map.input_count; ai++) {
                for (int bj = 0; bj < g_masters[j].channel_map.input_count; bj++) {
                    if (entries_overlap(&g_masters[i].channel_map.inputs[ai],
                                        &g_masters[j].channel_map.inputs[bj])) {
                        const ecat_channel_map_entry_t *a =
                            &g_masters[i].channel_map.inputs[ai];
                        plugin_logger_warn(&g_logger,
                            "IEC address overlap: %%I*%d.%d mapped by both "
                            "master '%s' and master '%s'",
                            a->byte_index,
                            a->bit_index >= 0 ? a->bit_index : 0,
                            g_masters[i].name, g_masters[j].name);
                        conflicts++;
                    }
                }
            }
            /* Check outputs */
            for (int ai = 0; ai < g_masters[i].channel_map.output_count; ai++) {
                for (int bj = 0; bj < g_masters[j].channel_map.output_count; bj++) {
                    if (entries_overlap(&g_masters[i].channel_map.outputs[ai],
                                        &g_masters[j].channel_map.outputs[bj])) {
                        const ecat_channel_map_entry_t *a =
                            &g_masters[i].channel_map.outputs[ai];
                        plugin_logger_warn(&g_logger,
                            "IEC address overlap: %%Q*%d.%d mapped by both "
                            "master '%s' and master '%s'",
                            a->byte_index,
                            a->bit_index >= 0 ? a->bit_index : 0,
                            g_masters[i].name, g_masters[j].name);
                        conflicts++;
                    }
                }
            }
        }
    }

    if (conflicts > 0) {
        plugin_logger_warn(&g_logger,
            "%d IEC address overlap(s) detected between masters. "
            "The last master in cycle order will overwrite shared addresses.",
            conflicts);
    }
}

/**
 * @brief Start all EtherCAT masters
 *
 * Iterates each configured master instance and runs through the startup
 * sequence. Returns success if at least one master reaches OPERATIONAL.
 */
int start_loop(void)
{
    int any_started = 0;

    for (int i = 0; i < g_master_count; i++) {
        ecat_master_instance_t *inst = &g_masters[i];

        int state = atomic_load(&inst->plugin_state);
        if (state != ECAT_STATE_IDLE && state != ECAT_STATE_STOPPED) {
            plugin_logger_error(&g_logger,
                "Master '%s': Cannot start - invalid state: %s",
                inst->name, ecat_state_to_string(state));
            continue;
        }

        if (start_single_master(inst) == 0) {
            any_started++;
        }
    }

    if (any_started == 0) {
        plugin_logger_error(&g_logger,
            "No EtherCAT masters started successfully");
        return -1;
    }

    warn_address_overlap();

    plugin_logger_info(&g_logger, "%d/%d EtherCAT master(s) started",
                       any_started, g_master_count);
    return 0;
}

/**
 * @brief Stop all EtherCAT masters
 */
void stop_loop(void)
{
    plugin_logger_info(&g_logger, "Stopping all EtherCAT masters...");

    for (int i = 0; i < g_master_count; i++) {
        stop_single_master(&g_masters[i]);
    }

    plugin_logger_info(&g_logger, "All EtherCAT masters stopped");
}

/**
 * @brief Cleanup plugin resources
 */
void cleanup(void)
{
    plugin_logger_info(&g_logger, "Cleaning up EtherCAT plugin...");

    for (int i = 0; i < g_master_count; i++) {
        ecat_master_instance_t *inst = &g_masters[i];
        int state = atomic_load(&inst->plugin_state);
        if (state != ECAT_STATE_STOPPED && state != ECAT_STATE_IDLE) {
            stop_single_master(inst);
        }
        pthread_mutex_destroy(&inst->slaves_mutex);
#if ECAT_ENABLE_MONITOR_THREAD
        pthread_mutex_destroy(&inst->soem_lock);
#endif
    }

    free(g_masters);
    g_masters = NULL;
    g_master_count = 0;

    plugin_logger_info(&g_logger, "EtherCAT plugin cleanup complete");
}

/**
 * @brief Called at the start of each PLC scan cycle
 *
 * Iterates all master instances and performs synchronous process data
 * exchange for each one that is in OPERATIONAL or RECOVERING state.
 */
void cycle_start(void)
{
    for (int i = 0; i < g_master_count; i++) {
        cycle_start_single(&g_masters[i]);
    }
}

/**
 * @brief Called at the end of each PLC scan cycle
 *
 * Output data is written to the IOmap at the beginning of cycle_start()
 * (before the exchange), so this hook is intentionally a no-op.
 */
void cycle_end(void)
{
    /* Outputs are written at the start of the next cycle_start() so they
     * are sent in the same SOEM exchange that receives fresh inputs. */
}

/*
 * =============================================================================
 * Async Command Handling (execute_command)
 * =============================================================================
 */

/**
 * @brief Validate a network interface name for safe use in SOEM calls.
 *
 * Accepts Linux names (e.g. "eth0") and Windows NPF device paths
 * (e.g. "\\Device\\NPF_{GUID}").  Writes a JSON error to @p response
 * on failure.
 *
 * @return 0 if valid, -1 if invalid (response already filled)
 */
static int validate_interface_name(const char *ifname, char *response, size_t response_size)
{
    size_t ifname_len = strlen(ifname);
    if (ifname_len == 0 || ifname_len >= ECAT_IFNAME_MAX) {
        snprintf(response, response_size, "{\"error\":\"invalid interface name length\"}");
        return -1;
    }
    if (!ecat_iface_validate(ifname, ECAT_IFACE_ANY_PLATFORM)) {
        snprintf(response, response_size, "{\"error\":\"invalid interface name format\"}");
        return -1;
    }
    return 0;
}

/**
 * @brief Check if any master is actively running on the bus
 *
 * Used by scan/test commands to refuse operation while masters are active.
 */
static bool any_master_active(void)
{
    for (int i = 0; i < g_master_count; i++) {
        int state = atomic_load(&g_masters[i].plugin_state);
        if (state == ECAT_STATE_OPERATIONAL || state == ECAT_STATE_RECOVERING ||
            state == ECAT_STATE_TRANSITIONING) {
            return true;
        }
    }
    return false;
}

/**
 * @brief Handle the "scan" command using a temporary SOEM context
 *
 * Creates a separate ecx_contextt (not the master's context) to scan
 * the bus for slaves. This allows scanning even when the master is not running.
 */
static int handle_scan_command(cJSON *root, char *response, size_t response_size)
{
    cJSON *params = cJSON_GetObjectItemCaseSensitive(root, "params");
    cJSON *iface = params ? cJSON_GetObjectItemCaseSensitive(params, "interface") : NULL;

    if (!iface || !cJSON_IsString(iface)) {
        snprintf(response, response_size, "{\"error\":\"missing 'interface' param\"}");
        return -1;
    }

    if (validate_interface_name(iface->valuestring, response, response_size) != 0)
        return -1;

    /* Refuse scan while any master is actively running on the bus */
    if (any_master_active()) {
        snprintf(response, response_size,
            "{\"error\":\"EtherCAT master is running. Stop the PLC before scanning.\"}");
        return -1;
    }

    /* Temporary SOEM context for scan (independent from master contexts) */
    ecx_contextt scan_ctx;
    memset(&scan_ctx, 0, sizeof(scan_ctx));

    if (!ecx_init(&scan_ctx, iface->valuestring)) {
        snprintf(response, response_size,
            "{\"error\":\"Failed to open interface '%s'\"}", iface->valuestring);
        return -1;
    }

    int slave_count = ecx_config_init(&scan_ctx);
    if (slave_count <= 0) {
        ecx_close(&scan_ctx);
        snprintf(response, response_size,
            "{\"status\":\"success\",\"devices\":[],\"message\":\"No slaves found\",\"slave_count\":0}");
        return 0;
    }

    /* Build JSON response with discovered slaves */
    cJSON *resp = cJSON_CreateObject();
    cJSON_AddStringToObject(resp, "status", "success");
    cJSON *devices = cJSON_AddArrayToObject(resp, "devices");

    for (int i = 1; i <= scan_ctx.slavecount; i++) {
        ec_slavet *s = &scan_ctx.slavelist[i];
        cJSON *dev = cJSON_CreateObject();
        cJSON_AddNumberToObject(dev, "position", i);
        cJSON_AddStringToObject(dev, "name", s->name);
        cJSON_AddNumberToObject(dev, "vendor_id", s->eep_man);
        cJSON_AddNumberToObject(dev, "product_code", s->eep_id);
        cJSON_AddNumberToObject(dev, "revision", s->eep_rev);
        cJSON_AddNumberToObject(dev, "serial_number", s->eep_ser);
        cJSON_AddStringToObject(dev, "state", "UNKNOWN");
        cJSON_AddNumberToObject(dev, "al_status_code", 0);
        cJSON_AddBoolToObject(dev, "has_coe", (s->mbx_proto & 0x04) != 0);
        cJSON_AddNumberToObject(dev, "input_bytes", 0);
        cJSON_AddNumberToObject(dev, "output_bytes", 0);
        cJSON_AddItemToArray(devices, dev);
    }

    char msg[128];
    snprintf(msg, sizeof(msg), "Found %d EtherCAT slave(s)", scan_ctx.slavecount);
    cJSON_AddStringToObject(resp, "message", msg);
    cJSON_AddNumberToObject(resp, "slave_count", scan_ctx.slavecount);

    char *json_str = cJSON_PrintUnformatted(resp);
    if (json_str) {
        snprintf(response, response_size, "%s", json_str);
        free(json_str);
    }
    cJSON_Delete(resp);

    ecx_close(&scan_ctx);
    return 0;
}

/**
 * @brief Handle the "list-interfaces" command
 *
 * Uses ec_find_adapters() from SOEM to enumerate network adapters.
 * Does not require a SOEM context or bus access.
 */
static int handle_list_interfaces_command(char *response, size_t response_size)
{
    ec_adaptert *adapters = ec_find_adapters();

    cJSON *resp = cJSON_CreateObject();
    cJSON_AddStringToObject(resp, "status", "success");
    cJSON *ifaces = cJSON_AddArrayToObject(resp, "interfaces");

    int count = 0;
    for (ec_adaptert *a = adapters; a != NULL; a = a->next) {
        cJSON *entry = cJSON_CreateObject();
        cJSON_AddStringToObject(entry, "name", a->name);
        cJSON_AddStringToObject(entry, "description", a->desc);
        cJSON_AddItemToArray(ifaces, entry);
        count++;
    }

    char msg[64];
    snprintf(msg, sizeof(msg), "Found %d network interface(s)", count);
    cJSON_AddStringToObject(resp, "message", msg);

    char *json_str = cJSON_PrintUnformatted(resp);
    if (json_str) {
        snprintf(response, response_size, "%s", json_str);
        free(json_str);
    }
    cJSON_Delete(resp);
    ec_free_adapters(adapters);

    return 0;
}

/**
 * @brief Handle the "test" command using a temporary SOEM context
 *
 * Creates a separate ecx_contextt to scan the bus and return info about
 * the slave at the requested position. Used by the Editor to test
 * connectivity to a specific device.
 */
static int handle_test_command(cJSON *root, char *response, size_t response_size)
{
    cJSON *params = cJSON_GetObjectItemCaseSensitive(root, "params");
    cJSON *iface = params ? cJSON_GetObjectItemCaseSensitive(params, "interface") : NULL;
    cJSON *pos = params ? cJSON_GetObjectItemCaseSensitive(params, "position") : NULL;

    if (!iface || !cJSON_IsString(iface)) {
        snprintf(response, response_size, "{\"error\":\"missing 'interface' param\"}");
        return -1;
    }
    if (!pos || !cJSON_IsNumber(pos)) {
        snprintf(response, response_size, "{\"error\":\"missing 'position' param\"}");
        return -1;
    }

    int position = pos->valueint;
    if (position < 1) {
        snprintf(response, response_size, "{\"error\":\"'position' must be a positive integer\"}");
        return -1;
    }

    if (validate_interface_name(iface->valuestring, response, response_size) != 0)
        return -1;

    /* Refuse test while any master is actively running on the bus */
    if (any_master_active()) {
        snprintf(response, response_size,
            "{\"error\":\"EtherCAT master is running. Stop the PLC before testing.\"}");
        return -1;
    }

    ecx_contextt test_ctx;
    memset(&test_ctx, 0, sizeof(test_ctx));

    if (!ecx_init(&test_ctx, iface->valuestring)) {
        snprintf(response, response_size,
            "{\"error\":\"Failed to open interface '%s'\"}", iface->valuestring);
        return -1;
    }

    int slave_count = ecx_config_init(&test_ctx);
    if (slave_count <= 0) {
        ecx_close(&test_ctx);
        snprintf(response, response_size,
            "{\"status\":\"success\",\"connected\":false,\"device\":null,"
            "\"message\":\"No EtherCAT slaves found on the network\"}");
        return 0;
    }

    if (position > test_ctx.slavecount) {
        char errmsg[128];
        snprintf(errmsg, sizeof(errmsg),
            "No device at position %d. Found %d slave(s).",
            position, test_ctx.slavecount);
        ecx_close(&test_ctx);
        snprintf(response, response_size,
            "{\"status\":\"error\",\"connected\":false,\"device\":null,"
            "\"message\":\"%s\"}", errmsg);
        return -1;
    }

    ec_slavet *s = &test_ctx.slavelist[position];

    cJSON *resp = cJSON_CreateObject();
    cJSON_AddStringToObject(resp, "status", "success");
    cJSON_AddBoolToObject(resp, "connected", 1);

    cJSON *dev = cJSON_CreateObject();
    cJSON_AddNumberToObject(dev, "position", position);
    cJSON_AddStringToObject(dev, "name", s->name);
    cJSON_AddNumberToObject(dev, "vendor_id", s->eep_man);
    cJSON_AddNumberToObject(dev, "product_code", s->eep_id);
    cJSON_AddNumberToObject(dev, "revision", s->eep_rev);
    cJSON_AddNumberToObject(dev, "serial_number", s->eep_ser);
    cJSON_AddStringToObject(dev, "state", "UNKNOWN");
    cJSON_AddNumberToObject(dev, "al_status_code", 0);
    cJSON_AddBoolToObject(dev, "has_coe", (s->mbx_proto & 0x04) != 0);
    cJSON_AddNumberToObject(dev, "input_bytes", 0);
    cJSON_AddNumberToObject(dev, "output_bytes", 0);
    cJSON_AddItemToObject(resp, "device", dev);

    char msg[128];
    snprintf(msg, sizeof(msg),
        "Successfully connected to %s at position %d", s->name, position);
    cJSON_AddStringToObject(resp, "message", msg);

    char *json_str = cJSON_PrintUnformatted(resp);
    if (json_str) {
        snprintf(response, response_size, "%s", json_str);
        free(json_str);
    }
    cJSON_Delete(resp);

    ecx_close(&test_ctx);
    return 0;
}

/**
 * @brief Local view of cycle diag values, already converted ns -> us.
 *
 * Used only by the JSON builders to avoid repeating the same atomic_load
 * sequence twice.  Cross-field tearing is acceptable for diagnostics.
 */
typedef struct {
    uint64_t cycle_count;
    uint64_t wkc_error_count;
    uint64_t noframe_count;
    uint64_t avg_cycle_us;
    uint64_t min_cycle_us;
    uint64_t max_cycle_us;
    uint64_t min_exchange_us;
    uint64_t max_exchange_us;
} ecat_diag_view_t;

static void load_diag_view(const ecat_master_instance_t *inst,
                           ecat_diag_view_t *out)
{
    out->cycle_count = atomic_load_explicit(&inst->diag.cycle_count,
                                            memory_order_relaxed);
    out->wkc_error_count = atomic_load_explicit(&inst->diag.wkc_error_count,
                                                memory_order_relaxed);
    out->noframe_count = atomic_load_explicit(&inst->diag.noframe_count,
                                              memory_order_relaxed);

    /* Single bus_cycle_ns measurement is exposed under both legacy names
     * (avg/min/max_cycle_us and min/max_exchange_us) for JSON compatibility
     * with the Editor.  Both pairs reflect the same exchange (send+receive)
     * timing — the duplicated naming is preserved to avoid breaking the
     * existing JSON contract. */
    int64_t avg = atomic_load_explicit(&inst->diag.avg_bus_cycle_ns,
                                       memory_order_relaxed);
    out->avg_cycle_us = (uint64_t)(avg / 1000);

    uint64_t min_bcn = atomic_load_explicit(&inst->diag.min_bus_cycle_ns,
                                            memory_order_relaxed);
    uint64_t max_bcn = atomic_load_explicit(&inst->diag.max_bus_cycle_ns,
                                            memory_order_relaxed);
    uint64_t min_us = (min_bcn == UINT64_MAX) ? 0 : min_bcn / 1000;
    uint64_t max_us = max_bcn / 1000;

    out->min_cycle_us    = min_us;
    out->max_cycle_us    = max_us;
    out->min_exchange_us = min_us;
    out->max_exchange_us = max_us;
}

/**
 * @brief Add a "slaves" JSON array using the published slaves_snapshot.
 *
 * @param diagnostics Include extra fields (al_state_raw) when true.
 */
static void add_slaves_json(ecat_master_instance_t *inst, cJSON *master,
                            int *out_count, bool diagnostics)
{
    ecat_slave_status_t local[ECAT_MAX_SLAVES];
    int n;

    pthread_mutex_lock(&inst->slaves_mutex);
    n = inst->slaves_snapshot_count;
    if (n > ECAT_MAX_SLAVES)
        n = ECAT_MAX_SLAVES;
    memcpy(local, inst->slaves_snapshot, sizeof(local));
    pthread_mutex_unlock(&inst->slaves_mutex);

    *out_count = n;

    cJSON *slaves = cJSON_AddArrayToObject(master, "slaves");
    for (int i = 0; i < n; i++) {
        const ecat_slave_status_t *ss = &local[i];
        cJSON *slave = cJSON_CreateObject();
        cJSON_AddNumberToObject(slave, "position", ss->position);
        cJSON_AddStringToObject(slave, "name", ss->name);
        cJSON_AddStringToObject(slave, "state", al_state_to_string(ss->al_state));
        if (diagnostics)
            cJSON_AddNumberToObject(slave, "al_state_raw", ss->al_state);
        cJSON_AddNumberToObject(slave, "al_status_code", ss->al_status_code);
        cJSON_AddNumberToObject(slave, "error_count", ss->error_count);
        cJSON_AddBoolToObject(slave, "has_error",
                              (ss->al_state & EC_STATE_ERROR) != 0 ||
                              ss->al_state != EC_STATE_OPERATIONAL);
        cJSON_AddItemToArray(slaves, slave);
    }
}

/**
 * @brief Build a JSON object for a single master's status.
 *
 * Reads counters/timing lock-free from inst->diag (atomic), and the
 * per-slave snapshot under slaves_mutex.  No interaction with the PLC
 * thread's hot path.
 */
static cJSON *build_master_status_json(ecat_master_instance_t *inst)
{
    ecat_plugin_state_t state =
        (ecat_plugin_state_t)atomic_load(&inst->plugin_state);
    int consecutive_wkc = atomic_load(&inst->consecutive_wkc_errors);
    int recovery_attempts = atomic_load(&inst->recovery_attempts);
#if ECAT_ENABLE_MONITOR_THREAD
    uint64_t exchange_skips = atomic_load(&inst->exchange_skips);
#else
    uint64_t exchange_skips = 0;
#endif

    ecat_diag_view_t diag;
    load_diag_view(inst, &diag);

    cJSON *master = cJSON_CreateObject();
    cJSON_AddStringToObject(master, "name", inst->name);
    cJSON_AddStringToObject(master, "plugin_state", ecat_state_to_string(state));
    cJSON_AddNumberToObject(master, "expected_wkc", inst->expected_wkc);

    int slave_count = 0;
    add_slaves_json(inst, master, &slave_count, false);
    cJSON_AddNumberToObject(master, "slave_count", slave_count);

    /* Cycle metrics */
    cJSON *metrics = cJSON_CreateObject();
    cJSON_AddNumberToObject(metrics, "cycle_count", (double)diag.cycle_count);
    cJSON_AddNumberToObject(metrics, "wkc_error_count", (double)diag.wkc_error_count);
    cJSON_AddNumberToObject(metrics, "noframe_count", (double)diag.noframe_count);
    cJSON_AddNumberToObject(metrics, "avg_cycle_us", (double)diag.avg_cycle_us);
    cJSON_AddNumberToObject(metrics, "min_cycle_us", (double)diag.min_cycle_us);
    cJSON_AddNumberToObject(metrics, "max_cycle_us", (double)diag.max_cycle_us);
    cJSON_AddNumberToObject(metrics, "min_exchange_us", (double)diag.min_exchange_us);
    cJSON_AddNumberToObject(metrics, "max_exchange_us", (double)diag.max_exchange_us);
    cJSON_AddNumberToObject(metrics, "consecutive_wkc_errors", consecutive_wkc);
    cJSON_AddNumberToObject(metrics, "recovery_attempts", recovery_attempts);
    cJSON_AddNumberToObject(metrics, "exchange_skips", (double)exchange_skips);
    cJSON_AddItemToObject(master, "metrics", metrics);

    return master;
}

/**
 * @brief Handle the "status" command
 *
 * Returns a snapshot of all masters' status via the "masters" array.
 */
static int handle_status_command(char *response, size_t response_size)
{
    cJSON *resp = cJSON_CreateObject();

    cJSON *masters_arr = cJSON_AddArrayToObject(resp, "masters");
    for (int i = 0; i < g_master_count; i++) {
        cJSON_AddItemToArray(masters_arr, build_master_status_json(&g_masters[i]));
    }

    char *json_str = cJSON_PrintUnformatted(resp);
    if (json_str) {
        snprintf(response, response_size, "%s", json_str);
        free(json_str);
    }
    cJSON_Delete(resp);

    return 0;
}

/**
 * @brief Build a JSON object for a single master's diagnostics.
 */
static cJSON *build_master_diagnostics_json(ecat_master_instance_t *inst)
{
    ecat_plugin_state_t state =
        (ecat_plugin_state_t)atomic_load(&inst->plugin_state);
    int consecutive_wkc = atomic_load(&inst->consecutive_wkc_errors);
    int recovery_attempts = atomic_load(&inst->recovery_attempts);
#if ECAT_ENABLE_MONITOR_THREAD
    uint64_t exchange_skips = atomic_load(&inst->exchange_skips);
#else
    uint64_t exchange_skips = 0;
#endif

    ecat_diag_view_t diag;
    load_diag_view(inst, &diag);

    cJSON *master = cJSON_CreateObject();
    cJSON_AddStringToObject(master, "name", inst->name);
    cJSON_AddStringToObject(master, "plugin_state", ecat_state_to_string(state));
    cJSON_AddNumberToObject(master, "expected_wkc", inst->expected_wkc);

    int slave_count = 0;
    add_slaves_json(inst, master, &slave_count, true);
    cJSON_AddNumberToObject(master, "slave_count", slave_count);

    /* Extended timing metrics */
    cJSON *timing = cJSON_CreateObject();
    cJSON_AddNumberToObject(timing, "cycle_count", (double)diag.cycle_count);
    cJSON_AddNumberToObject(timing, "wkc_error_count", (double)diag.wkc_error_count);
    cJSON_AddNumberToObject(timing, "noframe_count", (double)diag.noframe_count);
    cJSON_AddNumberToObject(timing, "avg_cycle_us", (double)diag.avg_cycle_us);
    cJSON_AddNumberToObject(timing, "min_cycle_us", (double)diag.min_cycle_us);
    cJSON_AddNumberToObject(timing, "max_cycle_us", (double)diag.max_cycle_us);
    cJSON_AddNumberToObject(timing, "min_exchange_us", (double)diag.min_exchange_us);
    cJSON_AddNumberToObject(timing, "max_exchange_us", (double)diag.max_exchange_us);
    cJSON_AddNumberToObject(timing, "configured_cycle_us",
                            inst->config.master.cycle_time_us);
    cJSON_AddNumberToObject(timing, "receive_timeout_us", inst->receive_timeout_us);
    cJSON_AddItemToObject(master, "timing", timing);

    /* Recovery info */
    cJSON *recovery = cJSON_CreateObject();
    cJSON_AddNumberToObject(recovery, "consecutive_wkc_errors", consecutive_wkc);
    cJSON_AddNumberToObject(recovery, "recovery_attempts", recovery_attempts);
    cJSON_AddNumberToObject(recovery, "max_recovery_attempts", ECAT_MAX_RECOVERY_ATTEMPTS);
    cJSON_AddNumberToObject(recovery, "wkc_error_threshold", ECAT_WKC_ERROR_THRESHOLD);
    cJSON_AddNumberToObject(recovery, "exchange_skips", (double)exchange_skips);
    cJSON_AddItemToObject(master, "recovery", recovery);

    /* Master configuration */
    cJSON *master_cfg = cJSON_CreateObject();
    cJSON_AddStringToObject(master_cfg, "interface", inst->config.master.interface);
    cJSON_AddNumberToObject(master_cfg, "cycle_time_us",
                            inst->config.master.cycle_time_us);
    cJSON_AddNumberToObject(master_cfg, "watchdog_timeout_cycles",
                            inst->config.master.watchdog_timeout_cycles);
    cJSON_AddItemToObject(master, "master_config", master_cfg);

    return master;
}

/**
 * @brief Handle the "diagnostics" command
 *
 * Returns detailed diagnostic information for all masters via the "masters" array.
 */
static int handle_diagnostics_command(char *response, size_t response_size)
{
    cJSON *resp = cJSON_CreateObject();

    cJSON *masters_arr = cJSON_AddArrayToObject(resp, "masters");
    for (int i = 0; i < g_master_count; i++) {
        cJSON_AddItemToArray(masters_arr,
                             build_master_diagnostics_json(&g_masters[i]));
    }

    char *json_str = cJSON_PrintUnformatted(resp);
    if (json_str) {
        snprintf(response, response_size, "%s", json_str);
        free(json_str);
    }
    cJSON_Delete(resp);

    return 0;
}

/**
 * @brief Execute an async command routed from the unix socket
 */
int execute_command(const char *command_json, char *response, size_t response_size)
{
    cJSON *root = cJSON_Parse(command_json);
    if (!root) {
        snprintf(response, response_size, "{\"error\":\"invalid JSON\"}");
        return -1;
    }

    cJSON *cmd = cJSON_GetObjectItemCaseSensitive(root, "command");
    if (!cmd || !cJSON_IsString(cmd)) {
        cJSON_Delete(root);
        snprintf(response, response_size, "{\"error\":\"missing 'command' field\"}");
        return -1;
    }

    int result = -1;
    if (strcmp(cmd->valuestring, "scan") == 0) {
        result = handle_scan_command(root, response, response_size);
    } else if (strcmp(cmd->valuestring, "list-interfaces") == 0) {
        result = handle_list_interfaces_command(response, response_size);
    } else if (strcmp(cmd->valuestring, "test") == 0) {
        result = handle_test_command(root, response, response_size);
    } else if (strcmp(cmd->valuestring, "status") == 0) {
        result = handle_status_command(response, response_size);
    } else if (strcmp(cmd->valuestring, "diagnostics") == 0) {
        result = handle_diagnostics_command(response, response_size);
    } else {
        snprintf(response, response_size, "{\"error\":\"unknown command '%s'\"}", cmd->valuestring);
    }

    cJSON_Delete(root);
    return result;
}
