/**
 * @file ethercat_plugin.h
 * @brief EtherCAT Plugin Interface for OpenPLC Runtime v4
 *
 * This plugin implements an EtherCAT master using the SOEM library.
 * It reads the EtherCAT configuration JSON generated by the OpenPLC Editor,
 * initializes the SOEM master, validates the bus topology against the
 * expected configuration, and manages process data exchange with slaves.
 *
 * Plugin lifecycle:
 *   init()        -> Load config, initialize logger [state: IDLE]
 *   start_loop()  -> Scan bus, write SDOs, map PDOs, transition to OP [state: OPERATIONAL]
 *   cycle_start() -> Exchange process data, read inputs into PLC buffers
 *   cycle_end()   -> (no-op, outputs written at start of next cycle)
 *   stop_loop()   -> Close master [state: STOPPED]
 *   cleanup()     -> Free resources
 *
 * Architecture:
 *   Process data exchange runs synchronously inside the PLC scan cycle
 *   via the cycle_start() hook. The bus cycle is fully synchronized with
 *   the PLC common_ticktime.
 *
 *   A background monitor thread (enabled by ECAT_ENABLE_MONITOR_THREAD)
 *   handles slave state checking and recovery outside the scan cycle.
 *   PLC thread and monitor thread serialize SOEM access via a per-instance
 *   pthread_mutex (soem_lock) initialized with PRIO_INHERIT.  The PLC
 *   uses pthread_mutex_trylock and skips a cycle (stale I/O data, no
 *   blocking) whenever the monitor is currently holding the lock.
 *
 * State machine: STOPPED -> IDLE -> SCANNING -> CONFIGURING ->
 *                TRANSITIONING -> OPERATIONAL <-> RECOVERING -> ERROR
 *
 * Commands: "scan", "status", "diagnostics"
 */

#ifndef ETHERCAT_PLUGIN_H
#define ETHERCAT_PLUGIN_H

/**
 * @brief Initialize the EtherCAT plugin
 *
 * Copies runtime args, initializes logger, loads and parses JSON config.
 *
 * @param args Pointer to plugin_runtime_args_t (freed after init returns)
 * @return 0 on success, -1 on failure
 */
int init(void *args);

/**
 * @brief Start the EtherCAT master
 *
 * Initializes SOEM, scans the bus, validates topology, writes SDOs,
 * maps PDOs, and transitions slaves to operational state.
 *
 * @return 0 on success, -1 on failure
 */
int start_loop(void);

/**
 * @brief Stop the EtherCAT master
 *
 * Transitions all slaves to INIT state and closes the network interface.
 */
void stop_loop(void);

/**
 * @brief Cleanup plugin resources
 */
void cleanup(void);

/**
 * @brief Called at the start of each PLC scan cycle
 *
 * Performs synchronous EtherCAT process data exchange:
 * writes outputs from the previous cycle, exchanges with slaves,
 * and reads fresh inputs into PLC buffers.
 */
void cycle_start(void);

/**
 * @brief Called at the end of each PLC scan cycle
 *
 * No-op. Outputs are written at the start of the next cycle_start()
 * to be sent together with the exchange that receives fresh inputs.
 */
void cycle_end(void);

/**
 * @brief Execute an async command
 *
 * Supported commands:
 *   - "scan": Scan bus for slaves (uses temporary SOEM context)
 *   - "status": Return current master/slave status snapshot
 *   - "diagnostics": Return detailed timing and recovery diagnostics
 *
 * @param command_json JSON string with "command" and optional "params" fields
 * @param response Buffer for JSON response
 * @param response_size Size of response buffer
 * @return 0 on success, -1 on error
 */
int execute_command(const char *command_json, char *response, size_t response_size);

#endif /* ETHERCAT_PLUGIN_H */
