/**
 * @file ethercat_config.h
 * @brief EtherCAT Plugin Configuration Structures and Parser Interface
 *
 * Defines the C structures that mirror the JSON configuration contract
 * generated by the OpenPLC Editor. The JSON is parsed using cJSON and
 * mapped into these structures for use by the EtherCAT master.
 */

#ifndef ETHERCAT_CONFIG_H
#define ETHERCAT_CONFIG_H

#include <stdbool.h>
#include <stdint.h>
#include <stdatomic.h>
#include <pthread.h>

#include "plugin_logger.h"
#include "soem/soem.h"

/* Maximum sizes */
#define ECAT_MAX_MASTERS      4
#define ECAT_MAX_SLAVES      64
#define ECAT_IOMAP_SIZE    8192
#define ECAT_MAX_CHANNELS    64
#define ECAT_MAX_PDO_ENTRIES 32
#define ECAT_MAX_PDOS        16
#define ECAT_MAX_SDOS        32
#define ECAT_MAX_NAME_LEN    64
#define ECAT_MAX_IEC_LOC_LEN 16

/**
 * @brief Recognized EtherCAT/CoE data types
 *
 * Covers integer, floating-point, and padding types found in PDO entries.
 * REAL32 and REAL64 are transported through the existing DWORD/LWORD buffers
 * (IEEE 754 bit patterns preserved by memcpy).
 */
typedef enum {
    ECAT_DTYPE_UNKNOWN,
    ECAT_DTYPE_BOOL,
    ECAT_DTYPE_INT8,
    ECAT_DTYPE_UINT8,
    ECAT_DTYPE_INT16,
    ECAT_DTYPE_UINT16,
    ECAT_DTYPE_INT32,
    ECAT_DTYPE_UINT32,
    ECAT_DTYPE_INT64,
    ECAT_DTYPE_UINT64,
    ECAT_DTYPE_REAL32,
    ECAT_DTYPE_REAL64,
    ECAT_DTYPE_PAD
} ecat_data_type_t;

/* Error codes */
#define ECAT_CONFIG_OK              0
#define ECAT_CONFIG_ERR_FILE       -1
#define ECAT_CONFIG_ERR_PARSE      -2
#define ECAT_CONFIG_ERR_MEMORY     -3
#define ECAT_CONFIG_ERR_INVALID    -4
#define ECAT_CONFIG_ERR_MISSING    -5

/**
 * @brief PDO entry definition
 *
 * Represents a single entry within a PDO (Process Data Object).
 * Entries with index "0x0000" are padding entries.
 */
typedef struct {
    char             index[12];        /* hex string e.g. "0x6000" */
    uint8_t          subindex;
    uint8_t          bit_length;
    char             name[ECAT_MAX_NAME_LEN];
    ecat_data_type_t parsed_type;      /* resolved from data_type string in JSON */
} ecat_pdo_entry_t;

/**
 * @brief PDO (Process Data Object) definition
 *
 * Contains the PDO index and its list of entries.
 * RxPDOs are written to the slave, TxPDOs are read from the slave.
 */
typedef struct {
    char             index[12];  /* hex string e.g. "0x1A00" */
    char             name[ECAT_MAX_NAME_LEN];
    ecat_pdo_entry_t entries[ECAT_MAX_PDO_ENTRIES];
    int              entry_count;
} ecat_pdo_t;

/**
 * @brief SDO configuration entry
 *
 * Defines an SDO (Service Data Object) parameter to be written
 * to a slave during configuration phase.
 */
typedef struct {
    char             index[12];        /* hex string e.g. "0x8000" */
    uint8_t          subindex;
    double           value;            /* stored as double; cast to target type at write time */
    ecat_data_type_t parsed_type;      /* resolved from data_type string in JSON */
    char             name[ECAT_MAX_NAME_LEN];
} ecat_sdo_config_t;

/**
 * @brief Channel mapping definition
 *
 * Maps a physical I/O channel to an IEC 61131-3 located variable.
 * Links the channel to its corresponding PDO entry.
 */
typedef struct {
    int      index;
    char     name[ECAT_MAX_NAME_LEN];
    char     type[20];         /* "digital_input", "analog_output", etc. */
    uint8_t  bit_length;
    char     iec_location[ECAT_MAX_IEC_LOC_LEN];
    char     pdo_index[12];
    char     pdo_entry_index[12];
    uint8_t  pdo_entry_subindex;
} ecat_channel_t;

/**
 * @brief Per-slave startup checks
 *
 * Controls which identity fields are validated against the SOEM slave list
 * during topology verification.
 */
typedef struct {
    bool     check_vendor_id;
    bool     check_product_code;
} ecat_startup_checks_t;

/**
 * @brief Per-slave addressing
 *
 * Controls slave addressing on the bus.
 */
typedef struct {
    uint16_t ethercat_address;    /* 0 = auto-assign */
} ecat_addressing_t;

/**
 * @brief Per-slave timeouts
 *
 * Configurable timeouts for SDO operations and state transitions.
 */
typedef struct {
    int      sdo_timeout_ms;           /* SDO operation timeout (default: 1000) */
    int      init_to_preop_timeout_ms; /* INIT->PRE-OP timeout (default: 3000) */
    int      safeop_to_op_timeout_ms;  /* SAFE-OP->OP timeout (default: 10000) */
} ecat_timeouts_t;

/**
 * @brief Per-slave watchdog configuration
 *
 * Controls Sync Manager and PDI watchdog behavior per slave.
 */
typedef struct {
    bool     sm_watchdog_enabled;      /* Sync Manager watchdog */
    int      sm_watchdog_ms;           /* SM watchdog timeout (default: 100) */
    bool     pdi_watchdog_enabled;     /* PDI watchdog */
    int      pdi_watchdog_ms;          /* PDI watchdog timeout (default: 100) */
} ecat_watchdog_t;

/**
 * @brief Per-slave Distributed Clocks configuration
 *
 * Controls DC SYNC0/SYNC1 signal generation per slave.
 */
typedef struct {
    bool     enabled;
    int      sync_unit_cycle_us;       /* 0 = use master cycle */
    bool     sync0_enabled;
    int      sync0_cycle_us;
    int      sync0_shift_us;
    bool     sync1_enabled;
    int      sync1_cycle_us;
    int      sync1_shift_us;
} ecat_dc_config_t;

/**
 * @brief EtherCAT slave configuration
 *
 * Complete configuration for a single EtherCAT slave device,
 * including identity, channel mappings, PDOs, SDOs, and per-slave
 * settings for timeouts, watchdogs, and distributed clocks.
 */
typedef struct {
    int               position;        /* ec_slave[position] in SOEM (1-based) */
    char              name[ECAT_MAX_NAME_LEN];
    char              type[20];        /* "coupler", "digital_input", etc. */
    uint32_t          vendor_id;
    uint32_t          product_code;
    uint32_t          revision;
    ecat_channel_t    channels[ECAT_MAX_CHANNELS];
    int               channel_count;
    ecat_sdo_config_t sdo_configs[ECAT_MAX_SDOS];
    int               sdo_count;
    ecat_pdo_t        rx_pdos[ECAT_MAX_PDOS];
    int               rx_pdo_count;
    ecat_pdo_t        tx_pdos[ECAT_MAX_PDOS];
    int               tx_pdo_count;
    ecat_startup_checks_t startup_checks;
    ecat_addressing_t     addressing;
    ecat_timeouts_t       timeouts;
    ecat_watchdog_t       watchdog;
    ecat_dc_config_t      dc;
    /* Abort master startup on any SDO write failure (default true). */
    bool                  strict_sdo;
} ecat_slave_t;

/**
 * @brief Master configuration parameters
 */
/** Maximum interface name length including null terminator.
 *  Linux names fit in IFNAMSIZ (16), but Windows NPF device paths such as
 *  \\Device\\NPF_{GUID} can reach ~55 characters. */
#define ECAT_IFNAME_MAX 128

typedef struct {
    char             interface[ECAT_IFNAME_MAX];
    int              cycle_time_us;
    int              receive_timeout_us;
    int              watchdog_timeout_cycles;
    char             log_level[8];
    /** SCHED_FIFO priority for the dedicated bus thread (1-99).
     *  Defaults to 90 — above typical IEC task priorities so the bus
     *  exchange isn't starved by a long PLC scan. */
    int              task_priority;
    /* Zero outputs and confirm INIT transition on stop_loop (default true). */
    bool             safe_close;
} ecat_master_config_t;

/**
 * @brief Diagnostics configuration
 */
typedef struct {
    bool             log_connections;
    bool             log_data_access;
    bool             log_errors;
    int              max_log_entries;
    int              status_update_interval_ms;
} ecat_diagnostics_config_t;

/**
 * @brief Top-level EtherCAT configuration
 *
 * Contains the master settings, flat list of slaves, and diagnostics config.
 *
 * WARNING: This struct is approximately 7 MB due to the inline slave array
 * with nested PDOs. It must be allocated statically or on the heap -- never
 * on the stack, as it would overflow most thread stacks.
 */
typedef struct {
    ecat_master_config_t      master;
    ecat_slave_t              slaves[ECAT_MAX_SLAVES];
    int                       slave_count;
    ecat_diagnostics_config_t diagnostics;
} ecat_config_t;

/**
 * @brief Parse EtherCAT configuration from a JSON file
 *
 * Reads and parses the JSON configuration file generated by the OpenPLC Editor.
 * The JSON has an array root format: [{ name, protocol, config }].
 * The "config" object is extracted and mapped to the ecat_config_t structure.
 *
 * @param config_path Path to the JSON configuration file
 * @param config Output configuration structure
 * @return ECAT_CONFIG_OK on success, negative error code on failure
 */
int ecat_config_parse(const char *config_path, ecat_config_t *config);

/**
 * @brief Validate a parsed configuration
 *
 * Checks required fields, value ranges, and IEC location format.
 *
 * @param config Configuration to validate
 * @return ECAT_CONFIG_OK on success, negative error code on failure
 */
int ecat_config_validate(const ecat_config_t *config);

/**
 * @brief Provide a logger for the config parser to use for diagnostic messages.
 *
 * Optional — when not set, the parser falls back to stderr.  Idempotent.
 * The pointer must remain valid for the lifetime of any subsequent
 * ecat_config_parse* call (typically the lifetime of the plugin).
 */
void ecat_config_set_logger(plugin_logger_t *logger);

/**
 * @brief Validation mode for interface names.
 *
 * Different callers need different rules: NIC tuning paths must receive
 * Linux-only names safe for /proc and external binaries (ethtool); the
 * scan and test commands accept any name the underlying socket layer
 * accepts, including Windows NPF device paths like "\Device\NPF_{GUID}".
 */
typedef enum {
    ECAT_IFACE_LINUX_STRICT,   /* alfanum + '_' '-', starts alpha, len 1..15 */
    ECAT_IFACE_ANY_PLATFORM    /* Linux + Windows NPF chars '\' '{' '}' '.' */
} ecat_iface_validate_mode_t;

/**
 * @brief Validate an interface name against the requested mode.
 *
 * @param iface NUL-terminated interface name (may be NULL — returns false).
 * @param mode  ECAT_IFACE_LINUX_STRICT or ECAT_IFACE_ANY_PLATFORM.
 * @return true if @p iface is a valid identifier under @p mode, false otherwise.
 */
bool ecat_iface_validate(const char *iface, ecat_iface_validate_mode_t mode);

/**
 * @brief Check whether an interface name is a safe Linux iface identifier.
 *
 * Thin wrapper kept for backward compatibility — equivalent to
 * ecat_iface_validate(iface, ECAT_IFACE_LINUX_STRICT).  Prefer the
 * explicit form in new code.
 *
 * @return true if safe, false otherwise.
 */
bool ecat_is_valid_iface_name(const char *iface);

/**
 * @brief Initialize configuration with default values
 *
 * @param config Configuration structure to initialize
 */
void ecat_config_init_defaults(ecat_config_t *config);

/**
 * @brief Parse a data type string into the corresponding enum value
 *
 * Recognizes standard CoE/EtherCAT type names and common aliases:
 *   "BOOL", "INT8"/"SINT", "UINT8"/"USINT", "INT16"/"INT",
 *   "UINT16"/"UINT", "INT32"/"DINT", "UINT32"/"UDINT",
 *   "INT64"/"LINT", "UINT64"/"ULINT",
 *   "REAL"/"REAL32"/"FLOAT", "LREAL"/"REAL64"/"DOUBLE", "PAD"
 *
 * @param str  NUL-terminated data type string (case-insensitive)
 * @return Matching ecat_data_type_t, or ECAT_DTYPE_UNKNOWN if unrecognized
 */
ecat_data_type_t ecat_parse_data_type(const char *str);

/*
 * =============================================================================
 * Plugin State Machine
 * =============================================================================
 */

/** Maximum number of recovery attempts before transitioning to ERROR state */
#define ECAT_MAX_RECOVERY_ATTEMPTS  5

/** Number of consecutive WKC errors before triggering recovery */
#define ECAT_WKC_ERROR_THRESHOLD    3

/**
 * Enable the background monitor thread for slave state checking and recovery.
 * When enabled, a low-priority thread periodically calls ecx_readstate() and
 * attempt_recovery() outside the PLC scan cycle, preventing overruns.
 * When disabled, no state monitoring or automatic recovery is performed
 * at runtime (the bus runs open-loop after reaching OPERATIONAL).
 *
 * Define to 0 to disable, 1 to enable.
 */
#ifndef ECAT_ENABLE_MONITOR_THREAD
#define ECAT_ENABLE_MONITOR_THREAD  1
#endif

/** Background monitor thread polling interval in milliseconds */
#define ECAT_MONITOR_INTERVAL_MS    500

/**
 * @brief EtherCAT plugin state machine states
 *
 * State transitions:
 *   STOPPED -> IDLE -> SCANNING -> CONFIGURING -> TRANSITIONING -> OPERATIONAL
 *   OPERATIONAL <-> RECOVERING
 *   RECOVERING -> ERROR (after max attempts)
 *   Any state -> STOPPED (via stop_loop)
 */
typedef enum {
    ECAT_STATE_IDLE,           /* After init(), before start_loop()         */
    ECAT_STATE_SCANNING,       /* ecx_init + ecx_config_init               */
    ECAT_STATE_CONFIGURING,    /* SDO writes + PDO mapping                 */
    ECAT_STATE_TRANSITIONING,  /* Slaves moving to SAFE-OP -> OP           */
    ECAT_STATE_OPERATIONAL,    /* Normal cyclic operation                   */
    ECAT_STATE_RECOVERING,     /* Attempting to recover slaves              */
    ECAT_STATE_ERROR,          /* Unrecoverable error                      */
    ECAT_STATE_STOPPED         /* After stop_loop() or before init()       */
} ecat_plugin_state_t;

/**
 * @brief Per-slave status snapshot for monitoring
 */
typedef struct {
    int      position;
    char     name[ECAT_MAX_NAME_LEN];
    uint16_t al_state;          /* EC_STATE_* from SOEM                    */
    uint16_t al_status_code;
    uint32_t error_count;
} ecat_slave_status_t;

/*
 * =============================================================================
 * Cycle Diagnostics
 * =============================================================================
 */

/**
 * @brief EWMA shift for the avg_*_ns counters in ecat_cycle_diag_t.
 *
 * The moving average update is:  avg += (sample - avg) / (1 << SHIFT),
 * an exponentially-weighted moving average with weight 1 / 2^SHIFT per
 * sample.  Effective window is ~2^SHIFT samples.
 *
 * SHIFT=5 -> window of 32 samples:
 *   - cycle 250 us -> 8 ms window  (smooths PDO-cycle jitter)
 *   - cycle 500 us -> 16 ms window
 *   - cycle 1 ms   -> 32 ms window (smooths transient bus events)
 *
 * Trade-off: smaller SHIFT is more responsive but noisier; larger SHIFT
 * smooths more but lags behind real drift.  5 is the sweet spot for
 * RT diagnostics where the operator wants "is the bus healthy now?",
 * not "what was the historical mean?".
 *
 * This replaces the integer Welford running mean previously used, which
 * stalls under integer division once cycle_count grows past ~10^7.
 */
#define ECAT_AVG_EWMA_SHIFT 5

/**
 * @brief Per-interface NIC tuning state captured by ecat_iface_state_apply().
 *
 * Holds the pre-EtherCAT NIC settings (ethtool coalescing + offloads) so
 * `ecat_iface_state_revert()` can roll them back on graceful shutdown,
 * and so the next runtime start can recover from a crash. Embedded in
 * each `ecat_master_instance_t`. See ethercat_iface_state.h for the
 * apply/revert API.
 */
typedef struct {
    char iface[ECAT_IFNAME_MAX];

    /* NIC tuning -- ethtool -C (coalescing) */
    bool coalescing_saved;
    int  rx_usecs;
    int  tx_usecs;

    /* NIC tuning -- ethtool -K (offloads) */
    bool offloads_saved;
    bool gro;
    bool gso;
    bool tso;
} ecat_iface_state_t;

/**
 * @brief Per-cycle timing diagnostics
 *
 * Updated lock-free by the dedicated bus thread.  Single-writer (bus
 * thread), multi-reader (monitor thread, execute_command handlers).
 * All fields are _Atomic so the writer never holds a mutex on the hot
 * path; readers tolerate cross-field tearing because these are
 * diagnostics, not values used in cross-field arithmetic.
 *
 * Two timing stories are tracked side by side:
 *
 *   - bus_cycle_ns / *_bus_cycle_ns  — work timing.  Measures the
 *     EtherCAT bus exchange (ecx_send_processdata +
 *     ecx_receive_processdata).  The IO memcpys around it are
 *     intentionally not measured (dozens of ns, dwarfed by the
 *     exchange).  Answers "how long does each cycle's work take?".
 *
 *   - period_ns / latency_ns        — scheduling timing.  period_ns
 *     is the observed gap between cycle starts (should equal the
 *     configured cycle on a healthy RT system).  latency_ns is the
 *     wake-up scheduling delay: how late after its absolute deadline
 *     the bus thread actually started.  Captured by the bus thread
 *     itself, so independent of the monitor's snapshot cadence.
 *     Answers "are we actually hitting our 1 ms cycle, and how late
 *     are we waking up?".
 *
 * avg_*_ns fields are EWMAs (see ECAT_AVG_EWMA_SHIFT), not historical
 * means.
 */
typedef struct {
    _Atomic(uint64_t) cycle_count;       /* total cycles executed              */
    _Atomic(uint64_t) wkc_error_count;   /* total WKC errors (wkc < expected)  */
    _Atomic(uint64_t) noframe_count;     /* total EC_NOFRAME (-1) errors       */

    /* Work timing -- bus exchange duration */
    _Atomic(uint64_t) bus_cycle_ns;      /* last send+receive duration (ns)    */
    _Atomic(uint64_t) max_bus_cycle_ns;  /* worst-case send+receive            */
    _Atomic(uint64_t) min_bus_cycle_ns;  /* best-case send+receive             */
    _Atomic(int64_t)  avg_bus_cycle_ns;  /* EWMA (see ECAT_AVG_EWMA_SHIFT)     */

    /* Scheduling timing -- period and wake-up latency */
    _Atomic(uint64_t) period_ns;         /* last observed cycle period (ns)    */
    _Atomic(uint64_t) max_period_ns;     /* worst-case period                  */
    _Atomic(uint64_t) min_period_ns;     /* best-case period                   */
    _Atomic(int64_t)  avg_period_ns;     /* EWMA                               */
    _Atomic(int64_t)  latency_ns;        /* last wake-up scheduling delay (ns) */
    _Atomic(int64_t)  max_latency_ns;    /* worst-case wake-up delay           */
    _Atomic(int64_t)  min_latency_ns;    /* best-case wake-up delay            */
    _Atomic(int64_t)  avg_latency_ns;    /* EWMA                               */
} ecat_cycle_diag_t;

/*
 * =============================================================================
 * I/O Channel Map and Transfer List Types
 * =============================================================================
 *
 * These types are defined here (rather than in ethercat_io.h) so that
 * ecat_master_instance_t can embed them directly, avoiding a circular
 * include between ethercat_config.h and ethercat_io.h.
 */

/* Maximum entries in a single direction of the channel map */
#define ECAT_MAX_MAP_ENTRIES 256

/**
 * @brief IEC 61131-3 data size qualifiers
 */
typedef enum {
    IEC_SIZE_BIT,    /* X -- single bit   */
    IEC_SIZE_BYTE,   /* B -- 1 byte       */
    IEC_SIZE_WORD,   /* W -- 2 bytes      */
    IEC_SIZE_DWORD,  /* D -- 4 bytes      */
    IEC_SIZE_LWORD   /* L -- 8 bytes      */
} iec_size_t;

/**
 * @brief IEC 61131-3 direction qualifiers
 */
typedef enum {
    IEC_DIR_INPUT,   /* I -- physical input  */
    IEC_DIR_OUTPUT   /* Q -- physical output */
} iec_dir_t;

/**
 * @brief Parsed IEC location -- result of parsing a string like "%IX0.3"
 */
typedef struct {
    iec_dir_t  direction;   /* I or Q            */
    iec_size_t size;        /* X, B, W, D, L     */
    int        byte_index;  /* byte address       */
    int        bit_index;   /* bit within byte (X only, 0-7; -1 otherwise) */
} iec_location_t;

/**
 * @brief Single entry in the channel map
 */
typedef struct {
    /* IOmap side */
    size_t   iomap_offset;     /* byte offset from IOmap base            */
    int      iomap_bit_offset; /* bit offset within the byte (0-7)       */
    uint8_t  bit_length;       /* channel width in bits                  */

    /* PLC side */
    iec_size_t      size;      /* IEC size qualifier                     */
    int             byte_index;/* byte index into PLC buffer             */
    int             bit_index; /* bit index (IEC_SIZE_BIT only, else -1) */
    ecat_data_type_t data_type;/* CoE data type from the PDO entry       */
} ecat_channel_map_entry_t;

/**
 * @brief Complete channel map -- separate arrays for inputs and outputs
 */
typedef struct {
    ecat_channel_map_entry_t inputs[ECAT_MAX_MAP_ENTRIES];
    int                      input_count;
    ecat_channel_map_entry_t outputs[ECAT_MAX_MAP_ENTRIES];
    int                      output_count;
} ecat_channel_map_t;

/**
 * @brief Single pre-resolved transfer entry
 */
typedef struct {
    void    *plc_ptr;           /* direct pointer to the PLC variable        */
    size_t   iomap_offset;      /* byte offset from IOmap base               */
    int      iomap_bit_offset;  /* bit offset within the byte (0-7)          */
    uint8_t  byte_count;        /* bytes to copy (1, 2, 4, or 8)            */
    bool     is_bit;            /* true for IEC_SIZE_BIT channels            */
} ecat_transfer_entry_t;

/**
 * @brief Complete transfer list -- separate arrays for inputs and outputs
 */
typedef struct {
    ecat_transfer_entry_t inputs[ECAT_MAX_MAP_ENTRIES];
    int                   input_count;
    ecat_transfer_entry_t outputs[ECAT_MAX_MAP_ENTRIES];
    int                   output_count;
} ecat_transfer_list_t;

/*
 * =============================================================================
 * Multi-Master Instance Structures
 * =============================================================================
 */

/**
 * @brief Per-master instance state
 *
 * Encapsulates ALL state for a single EtherCAT master, enabling
 * multiple independent masters on different network interfaces.
 * Must be heap-allocated (too large for stack: ~7MB per instance
 * due to the inline ecat_config_t slave array).
 */
typedef struct {
    /* Identity */
    char name[ECAT_MAX_NAME_LEN];       /* master name from JSON config */

    /* Configuration (parsed from JSON) */
    ecat_config_t config;

    /* SOEM context and IOmap — per-instance, NOT shared */
    ecx_contextt ecx_context;
    uint8_t iomap[ECAT_IOMAP_SIZE];
    int soem_initialized;
    size_t iomap_used_size;

    /* I/O channel map and transfer list (populated by start_loop) */
    ecat_channel_map_t channel_map;
    ecat_transfer_list_t transfer_list;

    /* State machine */
    _Atomic(int) plugin_state;          /* ecat_plugin_state_t */
    int expected_wkc;
    int receive_timeout_us;

    /* Diagnostics (updated by the bus thread) */
    ecat_cycle_diag_t diag;
    _Atomic(int) consecutive_wkc_errors;
    _Atomic(int) recovery_attempts;
    /* Counts ecx_writestate calls during recovery that returned wkc<=0
     * (request did not reach the slave -- link/cable issue, vs. slave
     * reachable but rejecting the state).  Distinguishes physical from
     * configuration recovery failures in the operator UI. */
    _Atomic(uint32_t) recovery_writestate_failures;
    uint64_t cycle_counter;

    /* Per-slave snapshot for queries via execute_command.
     *
     * The slave AL state lives in ecx_context.slavelist[], which is mutated
     * by the monitor thread during recovery.  Letting the JSON handlers read
     * slavelist[] directly would force them to take soem_lock, which the PLC
     * also tries to take on every cycle -- so each query would risk skipping
     * a PLC cycle.
     *
     * Instead the monitor publishes a small snapshot of the slave fields it
     * needs into slaves_snapshot[] under slaves_mutex (PRIO_INHERIT).  JSON
     * handlers take that mutex briefly; the PLC never touches it. */
    ecat_slave_status_t slaves_snapshot[ECAT_MAX_SLAVES];
    int                 slaves_snapshot_count;
    pthread_mutex_t     slaves_mutex;

#if ECAT_ENABLE_MONITOR_THREAD
    /* Monitor thread — per-instance.
     *
     * soem_lock serializes SOEM access between the PLC thread (cycle_start)
     * and the monitor thread (state checks, recovery).  The PLC thread uses
     * pthread_mutex_trylock and skips the cycle if the monitor is holding
     * the lock; the monitor takes the lock blockingly.  The lock is
     * initialized with PRIO_INHERIT to avoid priority inversion.
     */
    pthread_t monitor_thread;
    _Atomic(bool) monitor_running;
    pthread_mutex_t soem_lock;
    _Atomic(uint64_t) exchange_skips;
#endif

    /* Dedicated bus thread. Periodic at master.cycle_time_us, SCHED_FIFO
     * at the configured task_priority. Drives the synchronous SOEM
     * exchange independently of the IEC scan threads. Bus cycle stats
     * live on `inst->diag` and reach the editor via the existing
     * /api/discovery/ethercat/{runtime-status,diagnostics} routes. */
    pthread_t              bus_thread;
    _Atomic(bool)          bus_running;

    /* Per-iface external state (NIC tuning + IP-stack isolation).
     * Populated by ecat_iface_state_apply(); consumed by
     * ecat_iface_state_revert().  Includes its own iface name copy so
     * revert can run after config has been freed. */
    ecat_iface_state_t iface_state;
} ecat_master_instance_t;

/**
 * @brief Parse all EtherCAT master configurations from a JSON file
 *
 * Iterates ALL entries in the JSON array (not just the first).
 * Each entry with "protocol": "ETHERCAT" is parsed into a separate config.
 * Also extracts the master name from each entry.
 *
 * @param config_path  Path to the JSON configuration file
 * @param instances    Output array of master instances (only name + config are populated)
 * @param max_masters  Maximum number of masters to parse
 * @param out_count    Output: number of masters actually parsed
 * @return ECAT_CONFIG_OK on success, negative error code on failure
 */
int ecat_config_parse_all(const char *config_path,
                          ecat_master_instance_t *instances,
                          int max_masters,
                          int *out_count);

/**
 * @brief Convert plugin state enum to human-readable string
 *
 * @param state Plugin state value
 * @return Static string representation (e.g., "OPERATIONAL")
 */
const char *ecat_state_to_string(ecat_plugin_state_t state);

/**
 * @brief Get the size in bytes for a given EtherCAT data type
 *
 * Used for SDO write operations to determine the payload size.
 *
 * @param dt Data type enum value
 * @return Size in bytes (0 for UNKNOWN/PAD, 1 for BOOL)
 */
int ecat_data_type_size(ecat_data_type_t dt);

/**
 * @brief Convert a data type enum to a human-readable name (e.g. "INT16").
 *
 * Symmetric with ecat_state_to_string.  Used in log messages so the
 * structs no longer need to carry the original JSON string.
 *
 * @param dt Data type enum value
 * @return Static string ("UNKNOWN" for invalid or unrecognized values)
 */
const char *ecat_data_type_to_string(ecat_data_type_t dt);

#endif /* ETHERCAT_CONFIG_H */
